/*
 *  ======== config.c ========
 *  Configuration-specific definitions
 *
 *  DO NOT EDIT - This file is generated by the SysConfig tool for
 *  the TI Sensors in this application.
 */
#include <stdint.h>

#include "INA229.h"

#include "config.h"

/*
 *  ======== INA229_0 ========
 *  INA229 Sensor configuration settings
 */


static INA229_State INA229_0_state = {
    
    /* Configuration and Settings */
    .configRegister = (INA229_config_register_rst_NormalOperation | \
                       INA229_config_register_rstacc_NormalOperation | \
                       0x0000U | \
                       INA229_config_register_tempcomp_Shunttemperaturecompensationdisabled | \
                       INA229_config_register_adcrange_16384mV),
    .adcConfigRegister = (INA229_adc_config_register_mode_Continuousbusvoltageshuntvoltageandtemperature | \
                          INA229_adc_config_register_vbusct_1052us | \
                          INA229_adc_config_register_vshct_1052us | \
                          INA229_adc_config_register_vtct_1052us | \
                          INA229_adc_config_register_avg_1),
    .shuntCalRegister = 0x1000U,
    .shuntTempcoRegister = 0x0000U, /* TEMPCO is 0 ppm/°C */
    .diagAlrtRegister = (INA229_diag_alrt_register_alatch_Transparent | \
                         INA229_diag_alrt_register_cnvr_DisableconversionreadyflagonALERTpin | \
                         INA229_diag_alrt_register_slowalert_ALERTcomparisononnonaveragedADCvalue | \
                         INA229_diag_alrt_register_apol_Normalactivelowopendrain),
    .sovlRegister = 0x7FFFU,
    .suvlRegister = 0x8000U,
    .bovlRegister = 0x7FFFU,
    .buvlRegister = 0x0000U,
    .tempLimitRegister = 0x7FFFU,
    .pwrLimitRegister = 0xFFFFU,

    .adcrange = INA229_config_register_adcrange_16384mV, 
    .currentlsb = 0,

    /* Sensor's SPI bus and chip select ID */
    .busId = 0,
    .devCS = 0,

};
const INA229_Handle INA229_0 = &INA229_0_state;

