/*
 *  ======== INA229.c ========
 *  INA229 APIs for initialization and use of the INA229 peripheral
 *
 *  DO NOT EDIT - This file is generated by the SysConfig tool for
 *  the TI Sensors in this application.
 */

#include <stddef.h>
#include <stdint.h>

#include "INA229.h"
#include "mcu.h"

#define MSB(u16) (((u16) & 0xFF00U) >> 8)
#define LSB(u16) ((u16) & 0xFFU)

#define maxRegAddress 0x3F

// Register size in bytes
const uint8_t INA229_regSize[maxRegAddress+1] = {
                                            2,2,2,2,3,3,2,3,\
                                            3,5,5,2,2,2,2,2,\
                                            2,2,0,0,0,0,0,0,\
                                            0,0,0,0,0,0,0,0,\
                                            0,0,0,0,0,0,0,0,\
                                            0,0,0,0,0,0,0,0,\
                                            0,0,0,0,0,0,0,0,\
                                            0,0,0,0,0,0,2,2
};

/*
 *  ======== INA229_writeReg ========
 * Write register
 */
void INA229_writeReg(INA229_Handle sensor, uint8_t regAddr, uint16_t value)
{
    uint8_t txBuf[3] = {0}; //All writable registers are 2 bytes
    uint8_t rxBuf[3] = {0};

    txBuf[0] = regAddr << 2; //Address + write bit (ending in 0)
    txBuf[1] = MSB(value);
    txBuf[2] = LSB(value);
    mcu_spiTransfer(sensor->busId, sensor->devCS, 3, txBuf, rxBuf);

    //check for change in ADCRANGE 
    if(regAddr == INA229_config_register)
    {
        sensor->adcrange = value & INA229_config_register_adcrange_4096mV;
    }
}

/*
 *  ======== INA229_config ========
 * Configure device with current settings.
 */
void INA229_config(INA229_Handle sensor)
{
    //Initialize the bus containing this sensor
    mcu_spiInit(sensor->busId);

    //Write sensor Configuration Registers
    INA229_writeReg(sensor, INA229_config_register, sensor->configRegister);
    INA229_writeReg(sensor, INA229_adc_config_register, sensor->adcConfigRegister);
    INA229_writeReg(sensor, INA229_shunt_cal_register, sensor->shuntCalRegister);
    INA229_writeReg(sensor, INA229_shunt_tempco_register, sensor->shuntTempcoRegister);
    INA229_writeReg(sensor, INA229_diag_alrt_register, sensor->diagAlrtRegister);
    INA229_writeReg(sensor, INA229_sovl_register, sensor->sovlRegister);
    INA229_writeReg(sensor, INA229_suvl_register, sensor->suvlRegister);
    INA229_writeReg(sensor, INA229_bovl_register, sensor->bovlRegister);
    INA229_writeReg(sensor, INA229_buvl_register, sensor->buvlRegister);
    INA229_writeReg(sensor, INA229_temp_limit_register, sensor->tempLimitRegister);
    INA229_writeReg(sensor, INA229_pwr_limit_register, sensor->pwrLimitRegister);

}

/*
 *  ======== INA229_setCURRENT_LSB ========
 *  Set the CURRENT_LSB value used for calculations
 */
void INA229_setCURRENT_LSB(INA229_Handle sensor, float CURRENT_LSB)
{
    sensor->currentlsb = CURRENT_LSB;
}

/*
 *  ======== INA229_readReg ========
 *  Read register
 */
uint64_t INA229_readReg(INA229_Handle sensor, uint8_t regAddr)
{
    uint64_t value;
    int i;
    
    uint8_t txBuf[1] = {0};
    uint8_t rxBuf[6] = {0}; //max buffer size

    txBuf[0] = (regAddr << 2 ) | 0x01; //Address + read bit (ending in 1)

    //Read register
    mcu_spiTransfer(sensor->busId, sensor->devCS, INA229_regSize[regAddr]+1, txBuf, rxBuf);

    //Combine bytes
    value = 0; // initialize to 0, toss rxBuf[0];

    for(i = 1; i < INA229_regSize[regAddr]+1; i++)
    {
        value = (value << 8) | rxBuf[i];
    }

    return value;
}

/*
 *  ======== INA229_getVSHUNT_mV ========
 *  Get VSHUNT value (mV)
 */
float INA229_getVSHUNT_mV(INA229_Handle sensor)
{
    uint64_t value = INA229_readReg(sensor, INA229_vshunt_register);
    float data;

    //Remove reserved bits
    value = value >> 4;

    //Convert for 2's compliment and signed value
    if(value > 0x7FFFF)
    {
        data = (float)value - 0x100000;
    }
    else
    {
        data = (float)value;
    }

    //Convert to mV

    if(sensor->adcrange == INA229_config_register_adcrange_4096mV)
    {
        data = (data * 78.125) / 1000000;
    }
    else
    {
        data = (data * 312.5) / 1000000;
    }

    return data;
}

/*
 *  ======== INA229_getVBUS_V ========
 *  Get VBUS value (V)
 */
float INA229_getVBUS_V(INA229_Handle sensor)
{
    uint64_t value = INA229_readReg(sensor, INA229_vbus_register);
    float data;

    //Remove reserved bits
    value = value >> 4;

    //Convert for 2's compliment and signed value (though always positive)
    if(value > 0x7FFFF)
    {
        data = (float)value - 0x100000; //left for redundancy and error checking, should never get used
    }
    else
    {
        data = (float)value;
    }

    //Convert to V
    data = (data * 195.3125) / 1000000;

    return data;
}

/*
 *  ======== INA229_getDIETEMP_C ========
 *  Get DIETMEP value (C)
 */
float INA229_getDIETEMP_C(INA229_Handle sensor)
{
    uint64_t value = INA229_readReg(sensor, INA229_dietemp_register);
    float data;

    //Convert for 2's compliment and signed value
    if(value > 0x7FFF)
    {
        data = (float)value - 0x10000; 
    }
    else
    {
        data = (float)value;
    }

    //Convert to C
    data = (data * 7.8125) / 1000;

    return data;
}

/*
 *  ======== INA229_getDIETEMP_F ========
 *  Get DIETMEP value (F)
 */
float INA229_getDIETEMP_F(INA229_Handle sensor)
{
    float data = INA229_getDIETEMP_C(sensor);
    
    //Convert to F
    data = (data * (9/5)) + 32;

    return data;
}

/*
 *  ======== INA229_getCURRENT_signedLSB ========
 *  Get CURRENT value (signed value in LSBs)
 */
float INA229_getCURRENT_signedLSB(INA229_Handle sensor)
{
    uint64_t value = INA229_readReg(sensor, INA229_current_register);
    float data;

    //Remove reserved bits
    value = value >> 4;

    //Convert for 2's compliment and signed value 
    if(value > 0x7FFFF)
    {
        data = (float)value - 0x100000;
    }
    else
    {
        data = (float)value;
    }

    return data;
}

/*
 *  ======== INA229_getCURRENT_A ========
 *  Get CURRENT value (A)
 */
float INA229_getCURRENT_A(INA229_Handle sensor)
{
    float data = INA229_getCURRENT_signedLSB(sensor);

    data = data * sensor->currentlsb;

    return data;
}

/*
 *  ======== INA229_getPOWER_signedLSB ========
 *  Get POWER value (signed value in LSBs)
 */
float INA229_getPOWER_signedLSB(INA229_Handle sensor)
{
    uint64_t value = INA229_readReg(sensor, INA229_power_register);
    float data;

    data = (float)value;

    return data;
}

/*
 *  ======== INA229_getPOWER_W ========
 *  Get POWER value (W)
 */
float INA229_getPOWER_W(INA229_Handle sensor)
{
    float data = INA229_getPOWER_signedLSB(sensor);

    data = data * sensor->currentlsb * 3.2;

    return data;
}

/*
 *  ======== INA229_getENERGY_signedLSB ========
 *  Get ENERGY value (signed value in LSBs)
 */
double INA229_getENERGY_signedLSB(INA229_Handle sensor)
{
    uint64_t value = INA229_readReg(sensor, INA229_energy_register);
    double data;

    data = (double)value;

    return data;
}

/*
 *  ======== INA229_getENERGY_J ========
 *  Get ENERGY value (J)
 */
double INA229_getENERGY_J(INA229_Handle sensor)
{
    double data = INA229_getENERGY_signedLSB(sensor);

    data = data * sensor->currentlsb * 51.2;

    return data;
}

/*
 *  ======== INA229_getCHARGE_signedLSB ========
 *  Get CHARGE value (signed value in LSBs)
 */
double INA229_getCHARGE_signedLSB(INA229_Handle sensor)
{
    uint64_t value = INA229_readReg(sensor, INA229_charge_register);
    double data;

    //Convert for 2's compliment and signed value 
    if(value > 0x7FFFFFFFFF)
    {
        data = (double)value - 0x10000000000;
    }
    else
    {
        data = (double)value;
    }

    return data;
}

/*
 *  ======== INA229_getCHARGE_C ========
 *  Get CHARGE value (C)
 */
double INA229_getCHARGE_C(INA229_Handle sensor)
{
    double data = INA229_getCHARGE_signedLSB(sensor);

    data = data * sensor->currentlsb;

    return data;
}
